name: Validate HTML and CSS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - name: Validate HTML
      uses: w3c-validation-action@1.2.2
      with:
        path: index.html

    - name: Validate CSS
      uses: w3c-validation-action@1.2.2
      with:
        path: styles.css
