name: W3C Validation

on:
  push:
    branches:
      - main

jobs:
  validation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Validate HTML
        run: |
          set -e
          # Validate HTML
          html_output=$(curl -s -H "Content-Type: text/html; charset=utf-8" --data-binary "@index.html" https://validator.w3.org/nu/?out=text)
          echo "$html_output"
          echo "$html_output" | grep -q "There were errors" && { echo "HTML validation failed"; curl -s -H "Content-Type: text/html; charset=utf-8" --data-binary "@index.html" https://validator.w3.org/nu/?out=gnu; } || true

      - name: Validate CSS
        run: |
          css_output=$(curl -v -H "Content-Type: text/css; charset=utf-8" --data-binary "@styles.css" https://jigsaw.w3.org/css-validator/validator?profile=css3)
          echo "$css_output"
          echo "$css_output" | grep -q "Congratulations! No Error Found." || { echo "CSS validation failed"; } || true
