name: W3C Validation

on:
  push:
    branches:
      - main

jobs:
  validation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Validate HTML and CSS
        run: |
          # Validate HTML
          wget --post-data "fragment=$(cat index.html)" -q -O - https://validator.w3.org/nu/ \
            | grep "The document validates according to the specified schema(s)." || \
            echo "HTML validation failed"

          # Validate CSS
          wget --post-data "text=$(cat style.css)" -q -O - https://jigsaw.w3.org/css-validator/validator \
            | grep "No error found" || \
            echo "CSS validation failed"
