name: W3C Validation

on:
  push:
    branches:
      - main

jobs:
  validation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Validate HTML and CSS
        run: |
          # Validate HTML
          wget --post-data "fragment=$(cat index.html)" -q -O - https://validator.w3.org/nu/?out=json \
            | jq '.messages[] | "\(.type): \(.message) (\(.lastLine):\(.lastColumn))"' || \
            { echo "HTML validation failed"; wget --post-data "fragment=$(cat index.html)" -q -O - https://validator.w3.org/nu/?out=gnu; exit 1; }

      - name: Validate CSS
        uses: stefanzweifel/stylelint-action@v2
        with:
          path: styles.css
