name: W3C Validation

on:
  push:
    branches:
      - main

jobs:
  validation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Validate HTML and CSS
        run: |
          # Validate HTML
          curl -s -H "Content-Type: text/html; charset=utf-8" --data-binary "@index.html" https://validator.w3.org/nu/?out=text | grep -v "The document validates according to the specified schema(s)." || \
            { echo "HTML validation failed"; curl -s -H "Content-Type: text/html; charset=utf-8" --data-binary "@index.html" https://validator.w3.org/nu/?out=gnu; exit 1; }

          # Validate CSS
          curl -s -H "Content-Type: text/css; charset=utf-8" --data-binary "@styles.css" https://jigsaw.w3.org/css-validator/validator?profile=css3 -o /dev/null || \
            { echo "CSS validation failed"; exit 1; }
